general:
  timeout: 10 # in seconds
  timezone: "+0300" # format +/-HHMM
db:
  # full path to place where alert metadata will be keept
  path: /opt/alerthandler/db/alerts.db 
kuma:
  # ip or fqdn address of KUMA core
  address: kuma.abc.lab # use FQDN if server cert verification is needed
  # KUMA API port
  port: 7223 # 7223 - default
  # KUMA API token
  token: 00000000000000000000000000000000 # without 'Bearer'
  # KUMA Rest API CA
  ca: /opt/alerthandler/certs/core-external-ca.cert # keep empty if cert verification isn't needed
alertmanager:
  # Base alert manager url
  baseurl: https://alertmanager.abc.lab:9093/api/v2 # If you're not sure change only FQDN to your ip/fqdn
  # Client certificate
  client_cert: /opt/alerthandler/certs/client-cert.pem # If client Auth needed
  # Client private key
  client_key: /opt/alerthandler/certs/client-key.pem # If client Auth needed
  # Alertmanager CA cert
  server_ca: /opt/alerthandler/certs/ca-cert.pem # To verify server cert
