global:
  smtp_smarthost: '10.0.0.11:25'
  smtp_from: 'kuma@abc.lab'
  smtp_auth_username: 'kuma@abc.lab'
  smtp_auth_password: 'not_a_secret'
  smtp_require_tls: false

route:
  group_by: ['...']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'blackhole'
  routes:
    - receiver: 'webhook'
      matchers:
        - alertname =~ 'new_alert|updated|closed'
    - receiver: 'telegram'
      matchers:
        - notification_type =~ 'new_alert|closed'
    - receiver: 'email'
      matchers:
        - notification_type = 'assigned'

receivers:

  - name: 'webhook'
    webhook_configs:
      - url: 'http://10.0.0.10:6001/input'
        send_resolved: false

  - name: 'telegram'
    telegram_configs:
      - send_resolved: false
        bot_token: 0000000fffffffff 
        chat_id: 00000000 
        message: '{{ commonLabels.first_seen }} произошла сработка алерта {{ .commonLabels.alert_name }} с критичностью {{ .commonLabels.alert_priority }}'
        # Parse mode for telegram message, supported values are MarkdownV2, Markdown, HTML and empty string for plain text.
        parse_mode: "HTML"

  - name: 'email'
    email_configs:
      - to: '{{ .commonLabels.assignee }}@demo.lab'
        headers:
          Subject: '{{ .commonLabels.alert_name }}|{{ .commonLabels.alert_priority }}|{{ commonLabels.first_seen }}'
        text: '{{ .commonLabels.first_seen }} произошла сработка алерта {{ .commonLabels.alert_name }} с критичностью {{ .commonLabels.alert_priority }}'

  - name: 'blackhole' # empty receiver for blackholing alerts
