global:
  smtp_smarthost: "10.0.0.11:25"
  smtp_from: "kuma@abc.lab"
  smtp_auth_username: "kuma@abc.lab"
  smtp_auth_password: "not_a_secret"
  smtp_require_tls: false
  resolve_timeout: 20s

route:
  group_by: ['...']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'blackhole'
  
  routes:
    - receiver: 'webhook'
      continue: true
      matchers:
        - alertname =~ "new_alert|updated|closed"
        
    - receiver: 'telegram'
      continue: true
      matchers:
        - notification_type =~ "new_alert|closed"
        
    - receiver: 'email'
      matchers:
        - notification_type = "new_alert|closed|assigned"

receivers:

  - name: 'webhook'
    webhook_configs:
      - url: 'http://10.0.0.10:6001/input'
        send_resolved: false

  - name: 'telegram'
    telegram_configs:
      - send_resolved: false
        bot_token: 0000000fffffffff 
        chat_id: 00000000 
        message: '{{ .CommonLabels.first_seen }} произошла сработка алерта {{ .CommonLabels.alert_name }} с критичностью {{ .CommonLabels.alert_priority }}'
        # Parse mode for telegram message, supported values are MarkdownV2, Markdown, HTML and empty string for plain text.
        parse_mode: "HTML"

  - name: 'email'
    email_configs:
      - to: 'admin@abc.lab'
        headers:
          Subject: '{{ .CommonLabels.alert_name }} {{if eq .CommonLabels.notification_type "new_alert"}} fired! {{ else }} {{ .CommonLabels.notification_type }} {{ end }}'
        html: '{{ template "email.CUSTOM.html" . }}'

  - name: 'blackhole' # empty receiver for blackholing alerts

templates:
  - "/opt/alertmanager/email.tmpl"
