global:
  smtp_smarthost: "10.0.0.11:25" # specify host and port of SMTP server
  smtp_from: "kuma@abc.lab" # specify sender
  smtp_auth_username: "kuma@abc.lab" # specify username
  smtp_auth_password: "not_a_secret" # specify password
  smtp_require_tls: false
  resolve_timeout: 20s # don't touch it :)

route:
  group_by: ['...'] 
  group_wait: 10s 
  group_interval: 1m 
  repeat_interval: 10m 
  receiver: 'blackhole' 
  
  routes:
    - receiver: 'webhook'
      continue: true
      matchers:
        - notification_type =~ "new_alert|updated|closed" # specify your filter
        
#    - receiver: 'telegram'
#      continue: true
#      matchers:
#        - notification_type =~ "new_alert|closed"  # specify your filter
        
    - receiver: 'email'
      matchers:
        - notification_type =~ "new_alert|closed|assigned"  # specify your filter

receivers:

  - name: 'webhook'
    webhook_configs:
      - url: 'http://10.0.0.10:6001/input'  # specify webhook URL, for KUMA don't forget /input path
        send_resolved: false

# uncomment lines below if you want telegram integration

#  - name: 'telegram'
#    telegram_configs:
#      - send_resolved: false
#        bot_token: 0000000fffffffff # specify bot token
#        chat_id: 00000000  # specify chat id
#        message: '{{ .CommonLabels.first_seen }} произошла сработка алерта {{ .CommonLabels.alert_name }} с критичностью {{ .CommonLabels.alert_priority }}' # specify template for message

# Parse mode for telegram message, supported values are MarkdownV2, Markdown, HTML and empty string for plain text.

#        parse_mode: "HTML"

  - name: 'email'
    email_configs:
      - to: 'admin@abc.lab' # specify recipient
        headers:
          Subject: '{{ .CommonLabels.alert_name }} {{if eq .CommonLabels.notification_type "new_alert"}} fired! {{ else }} {{ .CommonLabels.notification_type }} {{ end }}'
        html: '{{ template "email.CUSTOM.html" . }}' # already persist

  - name: 'blackhole' # empty receiver for blackholing alerts

templates:
  - "/opt/alertmanager/email.tmpl" # already persist
